DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS type;
DROP TABLE IF EXISTS txn;
DROP TABLE IF EXISTS statement;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS mapping;

CREATE TABLE user (
  userID INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  first TEXT NOT NULL,
  last TEXT NOT NULL
);

CREATE TABLE type (
  typeID INTEGER PRIMARY KEY AUTOINCREMENT,
  enum TEXT NOT NULL,
  description TEXT DEFAULT NULL
);

CREATE TABLE txn (
  txnID INTEGER PRIMARY KEY AUTOINCREMENT,
  statementID INTEGER NOT NULL,
  userID INTEGER NOT NULL,
  categoryID INTEGER DEFAULT NULL,
  transDate DATE NOT NULL,
  description TEXT NOT NULL,
  amount INTEGER NOT NULL
);

CREATE TABLE statement (
  statementID INTEGER PRIMARY KEY AUTOINCREMENT,
  userID INTEGER NOT NULL,
  typeID INTEGER NOT NULL,
  billingMonth INTEGER NOT NULL,
  billingYear INTEGER NOT NULL
);

CREATE TABLE category (
  categoryID INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE mapping (
  pattern TEXT PRIMARY KEY NOT NULL,
  categoryID INTEGER
);
