insert into category(name) values("Groceries");
insert into category(name) values("Household");
insert into category(name) values("Clothing");
insert into category(name) values("Lunch");
insert into category(name) values("Coffee");
insert into category(name) values("Restaurants");
insert into category(name) values("Beauty");
insert into category(name) values("Pharmacy");
insert into category(name) values("Medical");
insert into category(name) values("Dental");
insert into category(name) values("Amazon");
insert into category(name) values("Prime/Hulu/Netflix");
insert into category(name) values("Mobile Phone");
insert into category(name) values("Time Warner");
insert into category(name) values("Gym");
insert into category(name) values("Transportation");
insert into category(name) values("Flights");
insert into category(name) values("Entertainment");
insert into category(name) values("Holiday");
insert into category(name) values("Electronics");
insert into category(name) values("Gifts");
insert into category(name) values("Donation");
insert into category(name) values("Seasonal");
insert into category(name) values("School");
insert into category(name) values("Financial Services");
insert into category(name) values("Utilities");
insert into category(name) values("Rent");
insert into category(name) values("Personal Development");
insert into category(name) values("Other");
insert into category(name) values("Payments");
insert into category(name) values("Baby");
insert into category(name) values("Salary");
insert into category(name) values("Savings");
insert into category(name) values("Investments");
